#In memory DB config. Comment this out for to test with real db
#spring.jpa.hibernate.ddl-auto: create
#spring.datasource.url: jdbc:h2:mem:embedded
#spring.datasource.username: h2

#Mysql local dev. Need to create a user and db schema first. See https://dzone.com/articles/docker-for-mac-mysql-setup
spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://localhost:3306/scanner?autoReconnect=true&useSSL=false
spring.datasource.username: changeme
spring.datasource.password: changeme

#Postgres on Heroku
#spring.jpa.hibernate.ddl-auto: update
#spring.datasource.driverClassName: org.postgresql.Driver
#spring.datasource.maxActive: 10
#spring.datasource.maxIdle: 5
#spring.datasource.minIdle: 2
#spring.datasource.initialSize: 5
#spring.datasource.removeAbandoned: true


spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: changeme
spring.mail.password: changeme
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

pop3:
  host: pop.gmail.com
  store: pop3
  serverStore: pop3s
  port: 995
  tls: true

system:
  sleep:
    short: 1000
    medium: 2000
    long: 8000

stockCharts:
    loginUrl: https://stockcharts.com/scripts/php/dblogin.php
    username: changeme
    password: changeme

alphaVantage:
    apiKeys: KA87B0YR4EUJ8MKB, 1DTKOY2QKA7MQNN1, CHT571LJ253B157I, FM1IK4BJWD021W3V, 
    timeout: 3000
        
tradingView:
    loginUrl: https://tradingview.com
    username: changeme
    password: changeme
