spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://localhost:3306/scanner?autoReconnect=true&useSSL=false
spring.datasource.username: admin
spring.datasource.password: password

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: myscannerapp365@gmail.com
spring.mail.password: <changeme>
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

system:
  sleep:
    short: 1000
    medium: 2000
    long: 8000

stockCharts:
    loginUrl: https://stockcharts.com/scripts/php/dblogin.php
    username: venky.kv@gmail.com
    password: <changeme>

alphaVantage:
    apiKey: KA87B0YR4EUJ8MKB
    timeout: 3000
        
tradingView:
    loginUrl: https://tradingview.com
    username: vikramkommaraju
    password: <changeme>
